# TODO: ajustar nombre del contenedor, separado por guiones
name: template-angular-20

services:
  # LOCAL: sirve en "/"
  app-local:
    image: node:22-alpine
    container_name: local
    hostname: local
    working_dir: /usr/src/app
    ports:
      - "4200:4200"
    volumes:
      - ..:/usr/src/app # monta tu repo en /usr/src/app
      - /usr/src/app/node_modules # evita que node_modules se solape
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # mejora watch en Docker/Win/Mac
      - WATCHPACK_POLLING=true
      - NG_CLI_ANALYTICS=false
    command: >
      sh -c "npm ci &&
             npm run start:local"
    restart: unless-stopped

  # DEV: subruta /plantilla-colibri-app-20
  app-dev:
    container_name: dev
    hostname: dev
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: development
        BASE_HREF: ${BASE_HREF} # Angular en subruta
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ROOT_DIR: ${ROOT_DIR}
      BASE_PATH: ${BASE_PATH} # Nginx en subruta
      ASSET_EXPIRES: -1
      ASSET_CACHE_CONTROL: "no-store, no-cache, must-revalidate, proxy-revalidate"
    ports: ["8081:80"]
    restart: unless-stopped

  # QA: subruta /plantilla-colibri-app-20
  app-qa:
    container_name: qa
    hostname: qa
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: qa
        BASE_HREF: ${BASE_HREF}
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ROOT_DIR: ${ROOT_DIR}
      BASE_PATH: ${BASE_PATH}
      ASSET_EXPIRES: 1h
      ASSET_CACHE_CONTROL: "public, max-age=3600, must-revalidate"
    ports: ["8082:80"]
    restart: unless-stopped

  # PROD: subruta /plantilla-colibri-app-20
  app-prod:
    container_name: prod
    hostname: prod
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: production
        BASE_HREF: ${BASE_HREF}
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ROOT_DIR: ${ROOT_DIR}
      BASE_PATH: ${BASE_PATH}
      ASSET_EXPIRES: ${ASSET_EXPIRES}
      ASSET_CACHE_CONTROL: ${ASSET_CACHE_CONTROL}
    ports: ["8083:80"]
    restart: unless-stopped
