# =========================
# Etapa 1: Build Angular
# =========================
FROM node:20 AS build
ENV NG_CLI_ANALYTICS="false"
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# local | development | qa | production
ARG BUILD_CONFIGURATION=production
ARG BASE_HREF=/plantilla-colibri-app-20/

# Compila (el builder puede dejar /browser dentro de /usr/share/nginx/html)
RUN npm run build -- \
    --configuration=${BUILD_CONFIGURATION} \
    --base-href=${BASE_HREF} \
    --output-path=/usr/share/nginx/html

# =========================
# Etapa 2: Nginx (runtime)
# =========================
FROM nginx:alpine

# Template que el entrypoint oficial renderiza con envsubst
COPY deploy/nginx.conf.template /etc/nginx/templates/default.conf.template

# Artefactos compilados
COPY --from=build /usr/share/nginx/html /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
