# =========================
# Etapa 1: Build Angular
# =========================
FROM node:20 AS build
ENV NG_CLI_ANALYTICS="false"
WORKDIR /app

# Dependencias (cacheable)
COPY package.json package-lock.json ./
RUN npm ci

# Código fuente
COPY . .

# Config de build (development | qa | production)
ARG BUILD_CONFIGURATION=production

# Salida directa a donde servirá Nginx
RUN npm run build -- \
    --configuration=${BUILD_CONFIGURATION} \
    --output-path=/usr/share/nginx/html

# =========================
# Etapa 2: Nginx (runtime)
# =========================
FROM nginx:alpine
ARG NGINX_CONF=nginx.prod.conf

# Nginx conf desde /deploy
COPY deploy/${NGINX_CONF} /etc/nginx/conf.d/default.conf

# Artefactos estáticos
COPY --from=build /usr/share/nginx/html /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
