name: templateangular20

services:
  app-local:
    profiles: ["local"]
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: local # <- importante para baseHref="/"
        NGINX_CONF: nginx.local.conf
    ports: ["8080:80"]
    restart: unless-stopped

  app-dev:
    profiles: ["dev"]
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: development
        NGINX_CONF: nginx.dev.conf
    ports: ["8081:80"]
    restart: unless-stopped

  app-qa:
    profiles: ["qa"]
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: qa
        NGINX_CONF: nginx.qa.conf
    ports: ["8082:80"]
    restart: unless-stopped

  app-prod:
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: production
        NGINX_CONF: nginx.prod.conf
    ports: ["8083:80"]
    restart: unless-stopped
