name: templateangular20

services:
  # LOCAL: sirve en "/"
  app-local:
    profiles: ["local"]
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: local
        BASE_HREF: "/" # Angular en raíz
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ROOT_DIR: ${ROOT_DIR}
      BASE_PATH: "" # Nginx en raíz
      ASSET_EXPIRES: -1
      ASSET_CACHE_CONTROL: "no-store, no-cache, must-revalidate, proxy-revalidate"
    ports: ["8080:80"]
    restart: unless-stopped

  # DEV: subruta /plantilla-colibri-app-20
  app-dev:
    profiles: ["dev"]
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: development
        BASE_HREF: ${BASE_HREF} # Angular en subruta
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ROOT_DIR: ${ROOT_DIR}
      BASE_PATH: ${BASE_PATH} # Nginx en subruta
      ASSET_EXPIRES: -1
      ASSET_CACHE_CONTROL: "no-store, no-cache, must-revalidate, proxy-revalidate"
    ports: ["8081:80"]
    restart: unless-stopped

  # QA: subruta /plantilla-colibri-app-20
  app-qa:
    profiles: ["qa"]
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: qa
        BASE_HREF: ${BASE_HREF}
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ROOT_DIR: ${ROOT_DIR}
      BASE_PATH: ${BASE_PATH}
      ASSET_EXPIRES: 1h
      ASSET_CACHE_CONTROL: "public, max-age=3600, must-revalidate"
    ports: ["8082:80"]
    restart: unless-stopped

  # PROD: subruta /plantilla-colibri-app-20
  app-prod:
    build:
      context: ..
      dockerfile: deploy/dockerfile
      args:
        BUILD_CONFIGURATION: production
        BASE_HREF: ${BASE_HREF}
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ROOT_DIR: ${ROOT_DIR}
      BASE_PATH: ${BASE_PATH}
      ASSET_EXPIRES: ${ASSET_EXPIRES}
      ASSET_CACHE_CONTROL: ${ASSET_CACHE_CONTROL}
    ports: ["8083:80"]
    restart: unless-stopped
